# Generated by Django 4.1.7 on 2026-05-01 13:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('hero_name', models.CharField(max_length=120)),
                ('activity_type', models.CharField(max_length=80)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_name', models.CharField(max_length=120)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['rank', '-points'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('universe', models.CharField(max_length=50)),
                ('captain', models.CharField(max_length=100)),
                ('motto', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('hero_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('favorite_activity', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['hero_name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('focus_area', models.CharField(max_length=120)),
                ('difficulty', models.CharField(max_length=40)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('assigned_to', models.CharField(max_length=120)),
                ('instructions', models.TextField()),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['title'],
            },
        ),
    ]
